pairs: pairs.o
	g++ -std=c++17 -o pairs pairs.o

pairs.o: pairs.cpp
	g++ -std=c++17 -c pairs.cpp

triplets: triplets.o
	g++ -std=c++17 -o triplets triplets.o

triplets.o: triplets.cpp
	g++ -std=c++17 -c triplets.cpp

clean:
	rm -rf *.o
